---
title: "Publications"
---

**Journal Articles:**

Friend, E. J., Gunter, S. A., Stamps, A., & Beck, P. A. (2025). Using respiratory gas flux and backward dietary energy partitioning to estimate energy intake by beef cattle when fed a high-concentrate diet. *Animal - Open Space, 4*, 100113. <https://doi.org/10.1016/j.anopes.2025.100113>

**Thesis:**

Friend, E. (2023). *Effects of hay maturity on the enteric methane emissions, forage intake ,energy metabolism and digestion by beef heifers* Oklahoma State University\]. ProQuest

**Abstracts:**

Beck, M.R., Gunter, S., Friend, E.J., Moffet, C.A., 2024. 7 Environmental sustainability of livestock systems in the southeastern U.S.: Opportunities and research gaps. Journal of Animal Science 102, 40. doi:10.1093/jas/skae019.046

Friend, E., Gunter, S.A., Moffet, C.A., Beck, P.A., 2022. 189 Effects of hay maturity on the enteric methane emission, intake, and energy metabolism by beef heifers. Journal of Animal Science 100, 86-87. doi:10.1093/jas/skac247.169

Friend, E.J., Gunter, S.A., Moffet, C.A., 2023. PSXIV-19 Gas flux by calves from dams identified as either high or low methane emitters. Journal of Animal Science 101, 539-540. doi: 10.1093/jas/skad281.634

Friend, E.J., Womack, A., Gunter, S.A., Beck, P.A., 2024. 149 Using respiratory gas flux and backward dietary energy partitioning to estimate energy intake by beef cattle fed a high concentrate diet. Journal of Animal Science 102, 76. doi:10.1093/jas/skae019.088

Friend, E. J., Womack, A., Gunter, S. A., & Beck, P. A. (2024). Using respiratory gas flux and backward dietary energy partitioning to estimate energy intake by beef cattle fed a high concentrate diet. *Journal of Animal Science, 102* (Supplement_1), 76. [https://doi.org/10.1093/jas/skae019.088](http://127.0.0.1:27715/#0)

Gunter, S., Friend, E.J., Beck, M.R., Moffet, C.A., 2024. 1 Use of the GreenFeed bait system to assist in measuring fecal output and digesta kinetics. Journal of Animal Science 102, 76-77. doi:10.1093.1093/jas/skae019.089

Gunter, S.A., Moffet, C.A., Friend, E.J., 2024. PSIX-22 Maternal methane, carbon dioxide, and oxygen flux compared with progeny gas flux. Journal of Animal Science 102, 735-735. doi:10.1093/jas/skae234.828

**Data sets:**

Gunter, S.A., Friend, E.J., 2025. Respiratory gas fluxes from cattle fed forage-based diet. Mendeley Data, V4, doi: 10.17632/46rwm84krf.4

Gunter, S.A., Grisby, Z., Beck, P.A., Friend, E.J., 2025. Effects of increasing supplementation rates of extruded distillers’ grain cubes on stocker steers production grazing native range in Bessie, OK and Fort Supply, Ok during the summer months in 2021 and 2022. Ag Data Commons. Dataset. https://doi.org/10.15482/USDA.ADC/29610539.v1

Gunter, S.A., Friend, E.J., Womack, A., Beck, P.A., 2025. Using respiratory gas flux and backward dietary energy partitioning to estimate energy intake by beef cattle when fed a high-concentrate diet. Mendeley Data, V2, doi:10.17632/7xw9p4syxr.2
